[package]
name = "token_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.16"
bincode = "1.3"
ic-cdk-macros = "0.16"
ic-stable-memory = "0.2"
ic-cdk-timers = "0.10" 
serde = { version = "1.0", features = ["derive"] }